#!/usr/bin/env python3

import json
import sys
from pathlib import Path
from collections import OrderedDict


def fail(msg: str) -> None:
    print(f"[packages] {msg}", file=sys.stderr)
    sys.exit(1)


def require(entry: dict, key: str) -> str:
    if key not in entry:
        fail(f"missing required key '{key}' in {entry}")
    return entry[key]


def emit_import_arduino_library(entry: dict) -> str:
    name = require(entry, "name")
    path = require(entry, "path")
    components = entry.get("components", [])
    comps = " ".join(components) if components else ""
    line = f"import_arduino_library({name} {path}"
    if comps:
        line += f" {comps}"
    line += ")\n"
    skip_link = entry.get("skip_link", False)
    return name, line, skip_link


def emit_import_arduino_library_git(entry: dict) -> str:
    name = require(entry, "name")
    url = require(entry, "url")
    tag = entry.get("tag", "master")
    subdir = entry.get("subdir", "")
    extras = entry.get("extras", [])
    extras_str = " ".join(extras) if extras else ""
    line = f'import_arduino_library_git({name} {url} {tag} "{subdir}"'
    if extras_str:
        line += f" {extras_str}"
    line += ")\n"
    skip_link = entry.get("skip_link", False)
    return name, line, skip_link


def emit_fetch_and_add_url_lib(entry: dict) -> str:
    name = require(entry, "name")
    url = require(entry, "url")
    path = entry.get("path", "")
    extras = entry.get("extras", [])
    extras_str = " ".join(extras) if extras else ""
    line = f'fetch_and_add_url_lib({name} {url} "{path}"'
    if extras_str:
        line += f" {extras_str}"
    line += ")\n"
    skip_link = entry.get("skip_link", False)
    return name, line, skip_link


def main() -> int:
    if len(sys.argv) != 3:
        fail("usage: generate_packages_cmake.py <packages.json> <out.cmake>")

    packages_json = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    if not packages_json.exists():
        fail(f"{packages_json} does not exist")

    data = json.loads(packages_json.read_text())

    declared = OrderedDict()
    emitted_lines = ["# Auto-generated by generate_packages_cmake.py. Do not edit.\n"]

    for entry in data.get("import_arduino_library", []):
        name, content, skip_link = emit_import_arduino_library(entry)
        emitted_lines.append(content)
        if not skip_link:
            declared[name] = None

    for entry in data.get("import_arduino_library_git", []):
        name, content, skip_link = emit_import_arduino_library_git(entry)
        emitted_lines.append(content)
        if not skip_link:
            declared[name] = None

    for entry in data.get("fetch_and_add_url_lib", []):
        name, content, skip_link = emit_fetch_and_add_url_lib(entry)
        emitted_lines.append(content)
        if not skip_link:
            declared[name] = None

    with out_path.open("w", encoding="ascii") as out:
        out.writelines(emitted_lines)
        joined = " ".join(declared.keys())
        out.write(f"set(PACKAGES_DECLARED {joined})\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())

